export const AUTH_ROLES = {
  USER: "USER",
  ADMIN: "ADMIN",
  MODERATOR: "MODERATOR",
  VENDOR: "VENDOR",
} as const;

export type AuthRole = typeof AUTH_ROLES[keyof typeof AUTH_ROLES];

export const AUTH_ERRORS = {
  UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "AUTH_USER_ALREADY_EXISTS",
  FORBIDDEN: "AUTH_FORBIDDEN",
  RATE_LIMIT_EXCEEDED: "AUTH_RATE_LIMIT_EXCEEDED",
} as const;
